/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostel;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        taikhoan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        matkhau = new javax.swing.JPasswordField();
        nuthienthimatkhau = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        nutthoatlogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Phòng Trọ");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tài Khoản :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        taikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taikhoanActionPerformed(evt);
            }
        });
        getContentPane().add(taikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 245, 33));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mật Khẩu :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 95, -1));

        matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkhauActionPerformed(evt);
            }
        });
        getContentPane().add(matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 245, 30));

        nuthienthimatkhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nuthienthimatkhau.setText("Show Pass");
        nuthienthimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuthienthimatkhauActionPerformed(evt);
            }
        });
        getContentPane().add(nuthienthimatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 102, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jButton1.setText("Đăng Nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 160, -1));

        nutthoatlogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nutthoatlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Close all jframe.png"))); // NOI18N
        nutthoatlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutthoatloginActionPerformed(evt);
            }
        });
        getContentPane().add(nutthoatlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login background.PNG"))); // NOI18N
        jLabel4.setText("c ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1300, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matkhauActionPerformed

    private void nuthienthimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuthienthimatkhauActionPerformed
     if(nuthienthimatkhau.isSelected())
     {
       matkhau.setEchoChar((char)0);
     }
     else
     {
          matkhau.setEchoChar('*');
     }
    }//GEN-LAST:event_nuthienthimatkhauActionPerformed

    private void taikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taikhoanActionPerformed

    private void nutthoatloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutthoatloginActionPerformed
        int thoat=JOptionPane.showConfirmDialog(null, "Ban Có Muốn Thoát ứng Dụng Không","Chọn",JOptionPane.YES_NO_OPTION);
        if(thoat==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_nutthoatloginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(taikhoan.getText().equals("admin123") && matkhau.getText().equals("123456"))
        {
            setVisible(false);
            new home().setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Bạn Đã Nhập Sai ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField matkhau;
    private javax.swing.JCheckBox nuthienthimatkhau;
    private javax.swing.JButton nutthoatlogin;
    private javax.swing.JTextField taikhoan;
    // End of variables declaration//GEN-END:variables
}
